export class UI{constructor(){this.el={app:document.getElementById('app')};this.el.app.innerHTML=`<div id="game"><canvas id="canvas"></canvas><div id="hud"><div class="top"><span id="stats">⭐ 0 · 🪙 0 · ❤️ 3</span><span id="level">Blumenhain 1/15</span></div><div id="objective"></div><div id="boss"><span id="bossName"></span><div><i id="bossFill"></i></div></div><div id="toast"></div></div><div id="screen" class="screen"><section><h1>SUPER MAMA JULIA 64</h1><h2>REBORN — V3</h2><p id="screenText">15 Level · 5 Welten · Bosse · Fähigkeiten · Secrets</p><div class="buttons"><button id="new">Neues Spiel</button><button id="continue">Fortsetzen</button><button id="saveReset">Save löschen</button></div></section></div><div id="touch"><div><button id="left">◀</button><button id="right">▶</button></div><div><button id="dash">↯</button><button id="action">⚡</button><button id="jump">▲</button></div></div></div>`;this.bindStyle()}
bindStyle(){const s=document.createElement('style');s.textContent=`*{box-sizing:border-box}html,body,#app,#game{margin:0;width:100%;height:100%;overflow:hidden;background:#05070d;color:white;font-family:system-ui,sans-serif}#game{position:relative}canvas{position:absolute;inset:0;width:100%;height:100%}#hud{position:absolute;inset:0;pointer-events:none;text-shadow:2px 2px #000}.top{display:flex;justify-content:space-between;padding:12px;font-weight:900}.top span{background:#0008;border:1px solid #fff3;border-radius:9px;padding:7px 10px}#objective{position:absolute;top:62px;left:12px;background:#0008;padding:7px 10px;border-radius:8px;font-size:13px}#boss{position:absolute;top:12px;left:50%;transform:translateX(-50%);width:260px;text-align:center;display:none}#boss div{height:12px;background:#171b26;border:1px solid white;border-radius:8px;overflow:hidden}#bossFill{display:block;height:100%;width:100%;background:linear-gradient(90deg,#d1003f,#ff6a00)}#toast{position:absolute;left:50%;top:50%;transform:translate(-50%,-50%);background:#090c16eF;border:2px solid #ffd43b;padding:14px 20px;border-radius:12px;color:#ffe47b;font-weight:900;opacity:0;transition:.18s}#toast.show{opacity:1}.screen{position:absolute;inset:0;display:flex;align-items:center;justify-content:center;text-align:center;background:#050812b8;backdrop-filter:blur(3px)}.screen section{width:min(700px,92%);padding:32px;background:#070b14df;border:1px solid #fff2;border-radius:20px;box-shadow:0 25px 90px #000}.screen h1{font-size:clamp(34px,7vw,70px);margin:0;color:#ffd43b;text-shadow:4px 4px #704b00;line-height:.9}.screen h2{margin:12px 0}.screen p{color:#d8dbea;line-height:1.5}.buttons{display:flex;gap:10px;justify-content:center;flex-wrap:wrap;margin-top:22px}.buttons button,#touch button{border:1px solid #fff4;background:#111827;color:#fff;border-radius:10px;padding:12px 18px;font-weight:900}.buttons button:first-child{background:#7d4b00;border-color:#ffd43b}#touch{position:fixed;bottom:10px;left:50%;transform:translateX(-50%);width:min(1100px,100%);display:flex;justify-content:space-between;padding:0 12px;pointer-events:none}#touch>div{display:flex;gap:8px;pointer-events:auto}#touch button{width:52px;height:52px;padding:0;border-radius:50%;font-size:20px;background:#08101acc;backdrop-filter:blur(6px)}@media(max-width:600px){#touch button{width:46px;height:46px}.top{font-size:11px}.screen section{padding:22px}}`;document.head.appendChild(s)}
setStats(s){this.q('#stats').textContent=`⭐ ${s.score} · 🪙 ${s.coins} · ❤️ ${s.lives} · 🔥 ${s.combo}`;if(s.level)this.q('#level').textContent=s.level}
setObjective(t){this.q('#objective').textContent=t}
showBoss(name,hp,max){this.q('#boss').style.display='block';this.q('#bossName').textContent=`👹 ${name}`;this.q('#bossFill').style.width=`${Math.max(0,hp/max)*100}%`}
hideBoss(){this.q('#boss').style.display='none'}
toast(t){const e=this.q('#toast');e.textContent=t;e.classList.add('show');clearTimeout(this.tt);this.tt=setTimeout(()=>e.classList.remove('show'),1300)}
showScreen(title,text,buttons=true){this.q('#screen').style.display='flex';this.q('#screen h1').textContent=title;this.q('#screen h2').textContent='';this.q('#screenText').textContent=text;this.q('.buttons').style.display=buttons?'flex':'none'}
hideScreen(){this.q('#screen').style.display='none'}
q(s){return document.querySelector(s)}}
